name: Get current run conclusion
description: Compute the conclusion of the current workflow run
author: 'l.boudreau@agendrix.com'
inputs:
  token:
    required: true
    description: "This should be a personal access token with access to your repository. Ex: ${{ secrets.GITHUB_TOKEN }}"
  deployments_outcome: 
    required: false
    description: "Outcome of the deployments. Accepted values are any values from DeploymentOutcome enum: https://github.com/agendrix/wait-for-ecs-service-deployment-action/blob/main/src/ecs/types.ts"
outputs:
  conclusion:
    description: Conclusion of the current workflow run
runs:
  using: 'node12'
  main: 'dist/index.js'
